URLS := \
	http://www.triplespark.net/elec/pdev/arm/minimalistic-hello-world-1.0.tar.gz \
	http://www.atmel.com/Images/doc6175.pdf \
	http://www.atmel.com/Images/doc6112.pdf \

include download.mk
all: download
clean: download_clean
