URLS := \
	http://www.triplespark.net/elec/pdev/arm/minimalistic-hello-world-1.0.tar.gz \
	http://www.atmel.com/Images/doc6175.pdf \
	http://www.atmel.com/Images/doc6112.pdf \
	http://www.atmel.com/Images/doc6120.pdf \
	http://www.atmel.com/Images/at91sam7s-ek.zip \
	http://www.atmel.com/Images/at91sam7x-ek.zip \
	http://www.atmel.com/Images/at91lib_20100901_softpack_1_5_svn_v8476.zip \
	http://morrow.ece.wisc.edu/ECE353/arm7tdmi_instruction_set_reference.pdf

include ../../download.mk
all: download
clean: download_clean
