/* libprim/media bindings for Scheme

   This file bridges the Scheme memory / control (exception) model
   with low-level C objects.  The function prototypes are mined to
   produce media.h_sc_prims contating media_table_init + macro defs.

   FIXME: 
     * this file should be autogenerated from the media/.h C objects. 
     * extend leaf objects with error handling mechanism
     * move some operations from scheme-specific to generic leaf.

 */

//#include "scheme.h"
#include <media/ffmpeg.h>
#include <leaf/bytes.h>
#include "media.h_sc_prims"
#include <media/xwindow.h>
#include <media/xv.h>
#include <media/glx.h>
#include <leaf/grid.h>
#include <media/gsl.h>
#include <media/yuv.h>

/*** X11 ***/

DEF_AREF_TYPE(xwindow)
DEF_AREF_TYPE(xdisplay)
DEF_AREF_TYPE(grid)
DEF_AREF_TYPE(grid_proc)

_ sc_make_display(sc *sc, _ ob) {
    return _sc_make_aref(sc, xdisplay_new(CAST(cstring, ob)));
}
_ sc_make_window(sc *sc) {
    return _sc_make_aref(sc, xwindow_new());
}
_ sc_window_config(sc *sc, _ win, _ disp) {
    xwindow_config(CAST(xwindow, win), CAST(xdisplay, disp));
    return VOID;
}
